Repository fga-eps-mds/2024.2-UnB-TV-Frontend, pull requests merged in 2025-01, with the labels that each got.

#5 Pull request das Issues #98 e #96
  src/app/components/background/background.component.css
  src/app/components/background/background.component.html
Labels: enhancement

#8 123 us04 mudar para tema dark mode
  src/app/app.module.ts
  src/app/components/background/background.component.css
  src/app/components/background/background.component.html
  src/app/components/background/background.component.ts
  src/app/pages/category-table/category-table.component.css
  src/app/pages/grid/grid.component.html
  src/app/pages/profile/profile.component.html
  src/app/pages/stream-view/stream-view.component.html
  src/app/pages/video-viewer/video-viewer.component.html
  src/assets/moon.svg
  src/assets/sun.svg
  src/assets/theme/theme.css
Labels: nfr

#9 146 bug05 modo dark mode na tela de admin
  src/app/pages/category-table/category-table.component.css
  src/app/pages/category-table/category-table.component.html
  src/app/pages/controle-super-admin/controle-super-admin.component.css
  src/app/pages/controle-super-admin/controle-super-admin.component.html
  src/app/pages/dashboard-category/dashboard-category.component.css
  src/app/pages/dashboard-category/dashboard-category.component.html
  src/app/pages/home-admin/home-admin.component.css
  src/app/pages/home-admin/home-admin.component.html
  src/app/pages/video-views/video-views.component.css
  src/app/pages/video-views/video-views.component.html
  src/assets/theme/theme.css
Labels: bug, MDS

#11 153 eh08 histórico de vídeos
  src/app/pages/record/record.component.css
  src/app/pages/record/record.component.html
  src/assets/down_arrow.svg
  src/assets/history_icon.svg
  src/assets/up_arrow.svg
Labels: enhancement, MDS
