Repository fga-eps-mds/2024.2-UnB-TV-Frontend, pull requests merged in 2025-02, with the labels that each got.

#16 147 US08 Feedback
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/environment/environment.test.ts
  src/app/environment/environment.ts
  src/app/pages/feedback-page/feedback-page.component.ts
  src/app/pages/feedback-page/feedback-page.css
  src/app/pages/feedback-page/feedback-page.html
  src/app/pages/feedback-page/feedback.component.spec.ts
  src/app/pages/profile/profile.component.css
  src/app/pages/profile/profile.component.html
  src/app/pages/profile/profile.component.ts
  src/app/services/feedback.service.spec.ts
  src/app/services/feedback.service.ts
  src/shared/model/feedback.model.ts
Labels: MDS, us

#15 Testes background
  src/app/components/background/background.component.spec.ts
  src/app/components/background/background.component.ts
  test-reports/TESTS.xml
Labels: testes

#17 129 EH04 Adicionar Responsividade
  src/app/pages/catalog/catalog.component.css
  src/app/pages/catalog/catalog.component.html
  src/app/pages/catalog/catalog.component.spec.ts
  src/app/pages/catalog/catalog.component.ts
Labels: enhancement, MDS
